[Config]
Dependencies=initrd

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main restricted universe multiverse

[Output]
Format=disk
Output=tinfoilcvm

[Content]
Hostname=tinfoil
Bootable=yes
Initrds=initrd
PackageDirectories=packages
RootPassword=!
Bootloader=uki
KernelModulesInitrd=no
WithDocs=false
CleanPackageMetadata=true
WithRecommends=false
Packages=
    systemd-boot-efi
    build-essential
    patch
    iproute2
    ca-certificates
    nftables
    iptables
    cryptsetup
    linux-generic
    linux-headers-generic
    nvidia-driver-open=595.71.05-1ubuntu1
    nvidia-persistenced=595.71.05-1ubuntu1
    nvidia-fabricmanager=595.71.05-1ubuntu1
    libnvidia-nscq=595.71.05-1ubuntu1
    nvattest=1.2.2.1780962352-1
    nvidia-container-toolkit=1.19.1-1

[Build]
ToolsTree=default
ToolsTreeDistribution=ubuntu
ToolsTreeRelease=resolute
WithNetwork=yes
Incremental=yes
