[Config]
Dependencies=initrd

[Distribution]
Distribution=ubuntu
Release=noble
Repositories=main restricted universe multiverse

[Output]
Format=disk
Output=tinfoilcvm

[Content]
Hostname=tinfoil
Bootable=yes
Initrds=initrd
PackageDirectories=packages
RootPassword=!
Bootloader=systemd-boot
Packages=
    systemd
    systemd-boot
    ubuntu-standard
    build-essential
    kmod
    nano
    systemd-resolved
    ca-certificates
    cryptsetup
    udev
    linux-generic-hwe-24.04
    linux-headers-generic-hwe-24.04
    nvidia-driver-580-open=580.126.20-1ubuntu1
    nvidia-persistenced=580.126.20-1ubuntu1
    nvidia-fabricmanager=580.126.20-1
    nvattest=1.2.0.1772475102-1
    libnvidia-nscq=580.126.20-1
    nvidia-container-toolkit=1.18.2-1
    docker-ce=5:29.3.0-1~ubuntu.24.04~noble
    docker-ce-cli=5:29.3.0-1~ubuntu.24.04~noble
    containerd.io=2.2.1-1~ubuntu.24.04~noble
    google-cloud-cli=559.0.0-0

[Build]
ToolsTree=default
ToolsTreeDistribution=ubuntu
ToolsTreeRelease=noble
WithNetwork=yes
Incremental=yes
