pool ntp-bootstrap.ubuntu.com iburst nts certset 1 maxsources 2 maxdelay 0.5 maxpoll 6
nosystemcert
ntstrustedcerts 1 /etc/chrony/nts-bootstrap-ubuntu.crt
nocerttimecheck 1
authselectmode require
makestep 0.1 1
maxchange 1.0 1 0
maxslewrate 1000
maxdrift 100
maxclockerror 100
maxdistance 0.5
leapsecmode slew
port 0
cmdport 0
bindcmdaddress /run/chrony/chronyd.sock
pidfile /run/chrony/chronyd.pid
