[Partition]
Type=root
Label=root
Format=ext4
CopyFiles=/
ExcludeFilesTarget=/etc/systemd
ExcludeFilesTarget=/usr/lib/systemd
ExcludeFilesTarget=/var/lib/systemd
Minimize=guess
SizeMinBytes=3G
Verity=data
VerityMatchKey=root
