version = 3
imports = []
disabled_plugins = [
    "io.containerd.cri.v1.images",
    "io.containerd.cri.v1.runtime",
    "io.containerd.differ.v1.erofs",
    "io.containerd.grpc.v1.cri",
    "io.containerd.grpc.v1.sandbox-controllers",
    "io.containerd.grpc.v1.sandboxes",
    "io.containerd.internal.v1.opt",
    "io.containerd.internal.v1.tracing",
    "io.containerd.monitor.container.v1.restart",
    "io.containerd.mount-handler.v1.erofs",
    "io.containerd.nri.v1.nri",
    "io.containerd.podsandbox.controller.v1.podsandbox",
    "io.containerd.sandbox.controller.v1.shim",
    "io.containerd.sandbox.store.v1.local",
    "io.containerd.snapshotter.v1.blockfile",
    "io.containerd.snapshotter.v1.devmapper",
    "io.containerd.snapshotter.v1.erofs",
    "io.containerd.snapshotter.v1.zfs",
    "io.containerd.tracing.processor.v1.otlp",
]

root = "/mnt/ramdisk/private/containerd/root"
state = "/mnt/ramdisk/private/containerd/run"
