[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main universe

[Output]
Format=none

[Content]
SourceDateEpoch=0
WithDocs=false
BuildPackages=
    ca-certificates=20260223
    golang-1.25-go=1.25.7-2

[Build]
BuildSources=../tinfoil:tinfoil
BuildSourcesEphemeral=yes
Incremental=yes
BuildDirectory=../build/builder-work
BuildKey=-
CacheDirectory=../build/builder-cache
PackageCacheDirectory=../build/builder-pkgcache
WorkspaceDirectory=../build/builder-workspace
WithNetwork=yes
Environment=
    CGO_ENABLED=0
    SOURCE_DATE_EPOCH=0
