load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "devicemapper",
    srcs = ["devicemapper.go"],
    importpath = "tinfoil/internal/devicemapper",
    visibility = ["//tinfoil:__subpackages__"],
    deps = ["@org_golang_x_sys//unix"],
)

go_test(
    name = "devicemapper_test",
    srcs = ["devicemapper_test.go"],
    embed = [":devicemapper"],
    deps = ["@org_golang_x_sys//unix"],
)
