package main

import (
	"crypto/tls"
	"encoding/json"
	"flag"
	"fmt"
	"net/http"
	"net/url"
	"os"

	log "github.com/sirupsen/logrus"
	"github.com/tinfoilsh/encrypted-http-body-protocol/identity"
	verifier "github.com/tinfoilsh/tinfoil-go/verifier/attestation"
	"golang.org/x/time/rate"

	"tinfoil/internal/boot"
	shimconfig "tinfoil/internal/config"
	"tinfoil/internal/key"
	"tinfoil/internal/key/online"
)

var version = "dev"

var (
	configFile         = flag.String("c", boot.ShimConfigPath, "Path to config file")
	externalConfigFile = flag.String("e", boot.ExternalConfigPath, "Path to external config file")
	dev                = flag.Bool("d", false, "Enable verbose logging")
	httpMode           = flag.Bool("i", false, "Use HTTP instead of HTTPS (insecure)")
)

func main() {
	flag.Parse()

	config, externalConfig, err := shimconfig.Load(*configFile, *externalConfigFile)
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	if config.Verbose || *dev {
		log.SetLevel(log.DebugLevel)
	}

	log.Printf("Starting tinfoil attestation shim %s: %+v", version, config)

	// API key validator
	var validator key.Validator
	if config.ControlPlane != "" {
		controlPlaneURL, err := url.Parse(config.ControlPlane)
		if err != nil {
			log.Fatalf("Failed to parse control plane URL: %v", err)
		}

		if config.Authenticated {
			validator, err = online.NewValidator(controlPlaneURL.JoinPath("api", "shim", "validate").String())
			if err != nil {
				log.Fatalf("Failed to initialize online API key verifier: %v", err)
			}
		} else {
			log.Warn("API key verification disabled (unauthenticated endpoint)")
		}
	} else {
		log.Warn("API key verification disabled (no control plane)")
	}

	// Load HPKE identity (generated by boot)
	serverIdentity, err := identity.FromFile(config.HPKEKeyFile)
	if err != nil {
		log.Fatalf("Failed to load HPKE identity: %v", err)
	}

	// Load attestation documents (generated by boot)
	att, err := loadAttestation()
	if err != nil {
		log.Fatalf("Failed to load attestation document: %v", err)
	}
	var attV3 json.RawMessage
	if data, err := os.ReadFile(boot.AttestationV3Path); err == nil {
		attV3 = data
	}

	// Load TLS certificate (generated by boot)
	cert, err := tls.LoadX509KeyPair(boot.TLSCertPath, boot.TLSKeyPath)
	if err != nil {
		log.Fatalf("Failed to load TLS certificate: %v", err)
	}

	// Load boot state (written by boot)
	bootState, err := boot.Load()
	if err != nil {
		log.Warnf("Failed to load boot state: %v", err)
	}

	tlsConfig := &tls.Config{
		GetCertificate: func(_ *tls.ClientHelloInfo) (*tls.Certificate, error) {
			return &cert, nil
		},
	}

	var rateLimiter *RateLimiter
	if config.RateLimit > 0 {
		rateLimiter = NewRateLimiter(rate.Limit(config.RateLimit), config.RateBurst)
	}

	listenAddr := fmt.Sprintf(":%d", config.ListenPort)
	httpServer := &http.Server{
		Addr:      listenAddr,
		Handler:   NewShimServer(validator, rateLimiter, att, attV3, serverIdentity, &cert, config, externalConfig, bootState),
		TLSConfig: tlsConfig,
	}

	log.Printf("Listening on %s", listenAddr)
	if *httpMode {
		log.Warn("Running in HTTP mode (insecure)")
		log.Fatal(httpServer.ListenAndServe())
	} else {
		log.Fatal(httpServer.ListenAndServeTLS("", ""))
	}
}

func loadAttestation() (*verifier.Document, error) {
	data, err := os.ReadFile(boot.AttestationPath)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", boot.AttestationPath, err)
	}
	var att verifier.Document
	if err := json.Unmarshal(data, &att); err != nil {
		return nil, fmt.Errorf("parsing attestation document: %w", err)
	}
	return &att, nil
}
