name: Build images

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build complete images
    runs-on: large
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: ./.github/actions/install-nix

      - name: Build checks and images
        shell: bash
        env:
          PATH: /nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        run: |
          set -Eeuo pipefail
          /nix/var/nix/profiles/default/bin/nix-build \
            --no-out-link -I . \
            -A checks \
            -A shipping-image \
            -A debug-image \
            -A cvm-compiler
